### ISSUE TITLE
add animation 

### ISSUE THREAD

**Issue by easa** [faslm/animated-material-login-page#1]
please add animation on a new branch and call it animation

**Comment by FatemehSalmani** [comment]
sorry ! I couldn't find a solution to this problem

**Comment by easa** [comment]
@faslm These links [scale-animation](https://materializecss.com/css-transitions.html), [entrance-animation](https://www.um.es/docencia/barzana/materializecss/transitions.html) are shown that materialize uses jQuery to make animation though. So this link of [animation login pages with jQuery](https://speedysense.com/login-signup-forms-using-html5-css3/) would help. BTW this google search query is helpful, google.com/search?q=jquery+animated+login+register.

**Comment by easa** [comment]
this is also a beautiful background using css 😍 https://codepen.io/davinci/pen/YxwwWd
